### ISSUE TITLE
problem with tickrate

### ISSUE THREAD

**Issue by bremen90** [MeteorTheLizard/MMM_M9k_Remastered#14]
as you know, all rp servers use a custom tickrate, usually 16 20 or 30
When using a custom tickrate, the rpm speed of the weapons changes
There is no problem in that, the problem is that for some reason there is some limitation and the weapons ignore the assigned rpm

It is as if it has a speed limit.
example, using server at tickrate 20
the famas gun has a 600 rpm limit and is quite slow.

Another problem that I found regarding the rpm, after several hours of being online the server, the weapons become slower when firing

the only solution is to restart the server. I guess it is the mathematical calculation that the server does and the memory use

**Comment by MeteorTheLizard** [comment]
Right now the weapons rely on timers which is likely to be changed in the future because it causes issues like you have mentioned. Timers do have the advantage of being less expensive, but are non-predictable and cause issues on varying tickrates as well as suffer from lag.

**Comment by MeteorTheLizard** [comment]
What I said previously is completely wrong, while there are timers in the code, they should not affect the firerate.

After further investigation, the problem is that M9kr makes use of CurTime (which is the only way possible AFAIK) to make timed events such as simulating RPM in a predictable and accurate manner. It is what everyone else uses for their weapons too so, yeah.

As stated in: https://wiki.facepunch.com/gmod/Global.CurTime
> This is internally defined as a float, and as such it will be affected by precision loss if your server uptime is more than 6 hours, which will cause jittery movement of players and props and inaccuracy of timers, it is highly encouraged to refresh or change the map when that happens (a server restart is not necessary).
> 
> This is NOT +as easy as it sounds to fix in the engine, so please refrain from posting issues about this

Additionally, CurTime is also affected by things such as the host_timescale.
However, having a lower (or higher) tickrate should not affect CurTime. I have tested this on a dedicated multiplayer server on varying tickrates 10, 16, 20, 33, 66, and 128. The weapon fire rates were the same.

Regarding the RPM limit, you can have one firing event per tick at max meaning there will always be a hard-cap for this. Since your servers tickrate is fairly low, the RPM limit is also fairly low. 20 ticks means it can't fire faster than 20 rounds per second.

None of these issues are fixable by me.
All you can do is restart your server frequently OR change the map every 6 hours and use a normal tickrate such as 33 or 66.
