### ISSUE TITLE
some weapons ignore ammo concommands

### ISSUE THREAD

**Issue by EntranceJew** [MeteorTheLizard/MMM_M9k_Remastered#15]
the following weapons ignore the console commands for starting with ammo loaded:
* m9k_m202
* m9k_rpg7
* m9k_matador
* m9k_mmm_peashooter
* m9k_mmm_peashooter_rifle

i recognize the gimmick of the latter half is that you discard the weapons when they're spent but they're amusing enough to warrant their own ammo types (peas); collecting additional peashooters of either type doesn't give you more ammo for the weapon(s) you already have, even though they're shooting the same projectile

you can also throw the `m9k_machete` but collecting additional ones does not give you more of them to throw like the `m9k_harpoon` does

additionally nitro is a throwable that you can obtain more of by spawning with a tool gun but it's the only one missing an entity that comes in a box (even though it should probably explode on breaking like frags / stickies)

edit: i did most of these tests on a 2 player game for multiplayer testing

**Comment by MeteorTheLizard** [comment]
All of the behavior you described is intentional. The `m9k_m202` and the `m9k_matador` do not have a proper reload animation which is why I decided to make them start with ammo and that's also why you throw them away on reload / when having used all of your rockets. This is the best design choice I was able to come up with. If you were to start with an empty `m9k_m202` or an empty `m9k_matador` you'd pick them up just to throw them away and magically gain a full one. I mean, that's how the reload works, but it would make even less sense.

The `m9k_rpg7` could technically follow the commands, however that would make it inconsistent to the other rocket launchers which is why it also starts fully loaded.

The peashooters originate from the first gamemode that I have ever made and have since then been completely reworked so that their code isn't total garbage. In said gamemode, you were able to kill NPCs with a single shot no matter how much damage that shot dealt as long as it was a headshot. The pistol version was a starter weapon that was meant to help beginners start out their journey and earn the gamemodes currency to buy new weapons. The peashooter rifle was a useless joke weapon that purely existed just because I was bored, but since it was technically as powerful as the peashooter pistol, it had to follow the same rules of not being able to be reloaded. The peashooters are meant to be one-time use non-reloadable. Since reloading these would had been utterly broken in said gamemode.

As for the `m9k_machete` and the `m9k_knife` both of these can be thrown, though they make use of different keys for that since you can hard-stab with the knife. It was a design choice to not be able to carry multiple machetes or knifes which is why you can't have more than one. I wanted to design the `m9k_harpoon` after the same logic, however after having come up with some new mechanics I decided that it would be better to be able to carry multiple harpoons, even though it makes no sense.

If I remember correctly, there was no model for the nitroglycerine ammo box which is why there is no ammo box for it.
